/**
 * Generates src/bloom-theme.css — a static `:root` / dark-mode block with
 * Willo's REAL resolved Bloom theme colors (not a hand-picked palette).
 *
 * Willo's own app (packages/frontend/app/_layout.tsx) configures Bloom with
 * a custom seed, not a named preset:
 *   <BloomProvider defaultMode="system" seed="#00537f" secondaryColor="#625007" tertiaryColor="#8e3205">
 * `theme.css` (@oxy.so/bloom/design-tokens/theme.css) only defines the
 * Tailwind alias layer (`--color-primary: var(--primary)`) — the actual
 * `--primary` etc. values are computed at runtime by Bloom's colour engine
 * from a seed, there is no static file with the raw hex/rgb values for an
 * arbitrary seed like Willo's. `buildSeedScopeVars` is Bloom's own
 * documented tool for exactly this: "pure — no React, no react-native — so
 * they run in a plain node/bun build script... instead of a hand-written
 * palette that drifts from the preset it claims to mirror" (see
 * node_modules/@oxy.so/bloom/src/theme/color-scope/seed-scope.ts).
 *
 * Willo Local's claim UI has no live theme switching (no logged-in user, no
 * theme picker) — it's a static device screen — so this runs ONCE, checked
 * in, and re-run only if Willo's seed colors ever change (see
 * packages/frontend/app/_layout.tsx in the main Willo monorepo for the
 * current values if this ever needs regenerating).
 *
 * Run: bun run scripts/generate-bloom-theme.ts
 */
import { buildSeedScopeVars, RADIUS, SHADOW_BOX } from "@oxy.so/bloom/design-tokens";

const SEED = "#00537f";
const SECONDARY_SEED = "#625007";
const TERTIARY_SEED = "#8e3205";

// Only the raw canonical tokens (--primary, --background, ...), not the
// --color-x Tailwind alias layer withScopeAliases also returns — this app
// doesn't use Tailwind, so those aliases would just be dead weight.
function canonicalOnly(vars: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(vars).filter(([key]) => !key.startsWith("--color-")));
}

function toCssBlock(vars: Record<string, string>, indent = "  "): string {
  return Object.entries(vars)
    .map(([key, value]) => `${indent}${key}: ${value};`)
    .join("\n");
}

const light = canonicalOnly(
  buildSeedScopeVars({ seed: SEED, mode: "light", secondarySeed: SECONDARY_SEED, tertiarySeed: TERTIARY_SEED }),
);
const dark = canonicalOnly(
  buildSeedScopeVars({ seed: SEED, mode: "dark", secondarySeed: SECONDARY_SEED, tertiarySeed: TERTIARY_SEED }),
);

// Bloom's radius/shadow scale (scales.ts, shadows.ts) — plain data, mode-
// independent, so these are written once at :root, not duplicated in the
// dark block. Same token names theme.css's @theme block uses
// (--radius-radius-20, --shadow-s) so this stays a drop-in match if a
// future Tailwind build ever gets added here.
const radiusVars = Object.fromEntries(
  Object.entries(RADIUS).map(([key, px]) => [`--radius-${key}`, `${px}px`]),
);
const shadowVars = Object.fromEntries(
  Object.entries(SHADOW_BOX).map(([key, value]) => [`--shadow-${key}`, value]),
);

const output = `/*
 * AUTO-GENERATED by scripts/generate-bloom-theme.ts — DO NOT EDIT BY HAND.
 * Willo's real resolved Bloom theme colors, computed by Bloom's own colour
 * engine (buildSeedScopeVars) from the exact seed Willo's app uses
 * (packages/frontend/app/_layout.tsx: seed #00537f, secondary #625007,
 * tertiary #8e3205), plus Bloom's radius/shadow scale (scales.ts,
 * shadows.ts) — see this script's own doc comment for why this is
 * generated rather than hand-picked or copied from a named preset.
 *
 * Responds to the OS/browser's prefers-color-scheme — this screen has no
 * theme picker (no logged-in user, no persisted preference to read).
 */

:root {
${toCssBlock(light)}
${toCssBlock(radiusVars)}
${toCssBlock(shadowVars)}
}

@media (prefers-color-scheme: dark) {
  :root {
${toCssBlock(dark, "    ")}
  }
}
`;

await Bun.write(new URL("../src/bloom-theme.css", import.meta.url), output);
console.log("Wrote src/bloom-theme.css");
console.log("light --primary:", light["--primary"]);
console.log("dark --primary:", dark["--primary"]);
